#!/usr/bin/env bash

set -e

case "$(uname)" in
    "Darwin") svg_open="open";;
    *) svg_open="firefox";;
esac

cabal run mem --constraint='libarchive -system-libarchive' -- +RTS -hT
hp2pretty mem.hp
$svg_open mem.svg
