#!/usr/bin/env bash

set -e

cabal build libarchive-test --enable-profiling --constraint='libarchive +low-memory +single-threaded'
"$(fd '^libarchive-test$' -t x -I)" +RTS -h
hp2pretty libarchive-test.hp
firefox libarchive-test.svg
