#!/usr/bin/env bash

set -e

case "$(uname)" in
    "Darwin") svg_open="open";;
    *) svg_open="firefox";;
esac

cabal run mem --enable-profiling -w ghc-9.0.1 --constraint='libarchive +static' -- +RTS -h
hp2pretty mem.hp
$svg_open mem.svg
